// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjhsX_JR1PrBqjxZ4A1VPpuUJpO9u6IWw',
    appId: '1:414936858136:web:2861231b07ea7fad72cd6d',
    messagingSenderId: '414936858136',
    projectId: 'med-go-e26db',
    authDomain: 'med-go-e26db.firebaseapp.com',
    storageBucket: 'med-go-e26db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4f2n_XjE7ztDgb-HDA0QTGydGlNb59I0',
    appId: '1:414936858136:android:8c8527ce425d405972cd6d',
    messagingSenderId: '414936858136',
    projectId: 'med-go-e26db',
    storageBucket: 'med-go-e26db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbv5_Ya3YUTHAlvcwdSElKKgbCyOXQzbU',
    appId: '1:414936858136:ios:375786219571f1b272cd6d',
    messagingSenderId: '414936858136',
    projectId: 'med-go-e26db',
    storageBucket: 'med-go-e26db.firebasestorage.app',
    iosBundleId: 'com.example.lifeMedicals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbv5_Ya3YUTHAlvcwdSElKKgbCyOXQzbU',
    appId: '1:414936858136:ios:375786219571f1b272cd6d',
    messagingSenderId: '414936858136',
    projectId: 'med-go-e26db',
    storageBucket: 'med-go-e26db.firebasestorage.app',
    iosBundleId: 'com.example.lifeMedicals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjhsX_JR1PrBqjxZ4A1VPpuUJpO9u6IWw',
    appId: '1:414936858136:web:dd1f6041e2d96c5d72cd6d',
    messagingSenderId: '414936858136',
    projectId: 'med-go-e26db',
    authDomain: 'med-go-e26db.firebaseapp.com',
    storageBucket: 'med-go-e26db.firebasestorage.app',
  );
}
